sudo: required
dist: trusty
language: ruby
rvm: 2.4.1
cache:
- bundler
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rspec
services:
- postgresql
deploy:
  provider: heroku
  app:
    master: johari-too
  run: rake db:migrate
  api_key:
    secure: kFqhJISEEGq2RQxNth3GDJXK5qh1/b7EqJjHd3XOhrdgugdEr51WIq3/HXZs9e1/MUAB93atpxe5SryTS/t6YDP7XXe8Fy+AjcHmQ+4SnW0kJeb2Qp8gVNvL0wYYgJUxwwuUMoslMw22NdFofo/DY9a0ZUvX9ePLGr1VSdaMgSvGzYmgrHyJifrKLvs8X5E0d4TSPCfQrafEZn+k3h118RVF8tIUXNfCd2WaUHNAxMmiTkJsl/FznY5d5GXT2rp2IUF1u7jJYc2RDQ2FNW4vh92jXungVzuqIq8nYOMmvbMY9SsCshqCFipDIIBEqYIkfyxiArkP5lw4d9iX5YUKdHMah/sQm1LWRMCFSCiq7MmsGMaA+QXn/JMbQXCXSZCycGOOyNIv2Bzna2tySEVcIwQZxNokzuLtfCBXBbjFMuv1OEqLlZuhWegoagWmhB8o7kQ/7vf1r7C0UGxov5lshOUSLjYGPPcVajBoiMDEnHMc+o4e9CujakF4QAxP8kPm70l11BnmQ47oqEWPyqLaJvcpJEsRs80OF5ObxLI/yngLvcNSHrQpnemUf6/NR6VUr4ZRP0C2neM24nlbOhXPEpyiOc6gqGF5ErGId3eQ6tlSGLHdRp+2noHVusvkvs0fkt/LOku9kyH5pJ0fBUY6lrFMqlWZzZWP65LE76mvzFI=
env:
  matrix:
  - secure: DhDhsIjKuAHSzHC4iFWiQwjSNyUQG7WN9yjKN6NA738U+pJLqHnEGhpYfbqWZvAuG4yNRfX42U0anLqNvQvcW6NkB5/jKBsrXeVt5mRWkoxO/pAU7Hc3Q5PCpNxjIBOS6y9ss/CmpAMLa+TCzraJ2M9IlzigB3Xx9qX/lS1kAxpDlKn+ZmBP3rXx1HXPTV94bfvF+0vEv5+M5j5IAYmaGckvxHWC9zBQ/KJ/V6PObRjcDduHB22V384UewYnstgmlOr6EUrP4sgpgSgdi1W9FYYHvOlq2VG98oeRCqf2uKIcFTkAkxRAQKzMhlCJgqWDPCvhSRkDjCz4wRbNvJILtboZ5Xod9vaiOJCtgSJ/Sa0wqHxfQHbKnlfUKBLAUV8QHeZSKbXo1aqWmBNsbDyeQrwXSjGze0aI8jfpYAbFt5jzDdnlYEygcAN8mJdf4wNYnoAUpHqKChSkKYLUVDl46sCNOa1CADaFFVTgrRsWT7JOGxe/2J6cxEPnx8IQ01CnqRU918lB+wNXDDsysEJUBCe1hoNH4VqEdVhweukJLCYdg6rS6q5jOpxoQijFCSdjtU3Adz1UPFEFOJ0oMsg+QosHaqbh+D0TPSXfZHENTQzfeApPQ6cAlVtLgTp4/Gx9rvFm62GoUZmYG7td/nEw7W6CcZrCSULbSE/gR6pLeFU=
  - secure: kX4BeZhMUSjOhKR7JBFlcSxhRCvvpUGOL6rqu4RXB2M4uhEvqfrH8FkEEf5Ew5WqCI41gn9arMFlimiPda3XrqwwmccswHi+hrGrEXsfsW6VyMi/jiXtKW7eZ1ItNDj+zDEwkCY/VC73jsp7zKk9ji7lhm2b5Ew6tvFZcr0RJUHqkkBPEumHBbRLK9ALBXKPEpBUAa52nFqXWTlOua9vxn/hHpYuj80TYuilccLOh1uZCBuIy6zSNuboRNS5wlZcF6O2A9z2Xme1ekH8jFmp7myZBfsI6rNcs6fQRhw+2mbbJPlvUltO6t0U7id23rwQQUbV2fKJQYbhjxgMsgvm8CVPwslG//56j4A4LsQ9oH2nmU6TqRmPRV1e+71mr+w5M7Q9pFSE+bElnbBi/E5Bows9ztYerJYp+o1yFAOSReDN5eapsA62/ajlB+O62UMbaUP6gEdoQ1f1v37WHtkgoPvDBYmg49ycmfM03QvZe/6zur6duWn+Fpywf94QmWmBb9t6wpidW7lrIh62pkEv+vDiwzHQNmh7wECWAfIgk9qUxCoTStz4UebrI4B6agAibeEbIPPhI19YU6/khbic4fjtM4tBLadv7saLGhv9xPwCXM18YXiHfwAjtbgoXD4HXdlGeQsdqDIBng2ZXZg3DnxpknWJgiexdeIszu9Kiwk=
  - secure: d0Mi20i/TDj4GuIVHy2O3XE8EKR3SxCVE8IeeUwsx0/zbMf9gH9v7vhobmcgkasss2URqd0hkqPP+RSGmKgJoWwEsLvQNX5op2elj4iLiUpLum/hmkrPaxmt1CTfEws5DTGsKHU0OlpW5A6sK5Ri0xV5xe3aLFRY+2QjnrQJYB+pkJiw2wt4v40SE3UXrjF0cOvsvFknMJrCzdWpiPu2ajdyvDdwFV1KtFiG0L6sBlCMW2/oCsSGz4en/DVM9zU1sMcrWxaolJCR9DtVhSK0T0T83UecSMvtg8rYzvY85tCyd2oYp1W1oxgAc5xzv/PxMiS0iE9iVwFnmaJT0Fw2X236B7TamvFuEwSXSoU/6xvlK1RSXV2bOJlmTIjQ2ab67bnUTSWCjxIRZBAGjRECTJflwSfBtKpYYoXhPL1nNrNMElvyREpd3vdvZnWpIdOMVujid3nLmUCMztQO9wdS+tRBj0EZ7cz1o99XtHsLUIAJWK0sczg1fWDm/8LyrXg5ivyb91cmn2dmhBKcb2UWYpptXNFUyFAdvQ+0bwysWqoY6cMq0Z9/TPU3rDVyL5dqJhUeUIEtWl0Y+MusMTX4hlzxOkzw4O5BGZN2qFJQGYiezobGRq1ykR2T6zHVEbOoSjx9IV93Of+2jk+M4unjsDnTvOccdl10r/j/gsLAnR0=
