sudo: required
dist: trusty
language: ruby
rvm: 2.4.1
cache:
- bundler
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rspec
services:
- postgresql
deploy:
  provider: heroku
  app:
    master: johari-too
  run: rake db:migrate
  api_key:
    secure: kFqhJISEEGq2RQxNth3GDJXK5qh1/b7EqJjHd3XOhrdgugdEr51WIq3/HXZs9e1/MUAB93atpxe5SryTS/t6YDP7XXe8Fy+AjcHmQ+4SnW0kJeb2Qp8gVNvL0wYYgJUxwwuUMoslMw22NdFofo/DY9a0ZUvX9ePLGr1VSdaMgSvGzYmgrHyJifrKLvs8X5E0d4TSPCfQrafEZn+k3h118RVF8tIUXNfCd2WaUHNAxMmiTkJsl/FznY5d5GXT2rp2IUF1u7jJYc2RDQ2FNW4vh92jXungVzuqIq8nYOMmvbMY9SsCshqCFipDIIBEqYIkfyxiArkP5lw4d9iX5YUKdHMah/sQm1LWRMCFSCiq7MmsGMaA+QXn/JMbQXCXSZCycGOOyNIv2Bzna2tySEVcIwQZxNokzuLtfCBXBbjFMuv1OEqLlZuhWegoagWmhB8o7kQ/7vf1r7C0UGxov5lshOUSLjYGPPcVajBoiMDEnHMc+o4e9CujakF4QAxP8kPm70l11BnmQ47oqEWPyqLaJvcpJEsRs80OF5ObxLI/yngLvcNSHrQpnemUf6/NR6VUr4ZRP0C2neM24nlbOhXPEpyiOc6gqGF5ErGId3eQ6tlSGLHdRp+2noHVusvkvs0fkt/LOku9kyH5pJ0fBUY6lrFMqlWZzZWP65LE76mvzFI=
env:
  global:
  - secure: ZQ/XU7TMQl+Hy2EQd3qq0T+mR71MpI/bNSMPXcQPEt5eXDgRsOUtrNsMTN4RS6QVXmzF6N4wJBCIbtxepYWlmK37WeVs8gByNRblOXJJd6cRA21wjkcMyy12Zwdce/qXFBvNNjyu1MN3K36XPnBeSV+0e8hEysz1KyyfSM5NXs8QRv/zgnqpf5ABFXFbUvAl+HObAOt1s4O92eKIoTgZCsv5GvqIgjK924mrfTH9ecAYyNNoLRpAd77MUwhrdNYK90qKUZUVqghG8aMoigsUfI3oVm0XeszeQP0T1V5cjqiMeEZn+wDvMRhM1qqXt4uQ81KaP0O8zh6GG6RX7OkyspRHdrSwnxmhwexdexFM3NtqqmwdWpuq8bkFsOBjx2mBGpA3lReB69vn9DUPNMxKKKbPtBVy6NcCDLl6vIqR0mHgRa/GIyK0Uq51C+XnUfKi9aUXrSJMu7rDvK1qcjSXBqBtoKSmvVALQIyUvGh6rlQ7KDo9UyxqxWQpR55MgLay81r+EffhD85pJ6HVEQQOvu3plfWHx+sCxY3qr6ewBvLC33YouuP3yo6+TQUCqrjVWESZfnJNRFMFpNybPMGaGSkk9zIH5WgyklGVkOBX7wRO5E54YSnwmWLBLOm6NRXRU//A5/1VMcXDF3JcNYQq2FmhD6IoCDbCa5zzfngbsq4=
  - secure: Z6i9W5d7EZV0sYJL4Y2hr2AnnFMGxwz/n2BXSiO4Y5QtFwy0rFoQC5I4EWsIm9ap7NlYqAyvVxJFgKlk1oA4NNAj7vJaSA2VrdzHWijSTHrULMN4ODYcWoepuPWrrIaT4nQTVzLSSoTBsbMYEKoOBXmNKuYGOKSexZdtAXluqQVO4ypaPstknwdyKG6nl84FTFANiVyyBTODBdh9lrNwkiu4TYfOs5poSHw6cZ6MYvkiLL4/R7R1Tbk4r+IoxSY71MrNFNsWw5Yi2mqDUF0bAVQ90QxYDJl/cspXgyNL3UKlkudLu2gZ0XiR3ch9nBq7eT/7k90rHLGcF+U4oQ3eVTFn+ubZAer8Ya+tTauSySJJ29RGM7eyDeuYFOqRDFJQtSrNjk7TLkY1cB7cnKBQZ8OPuNkl15ewiuhWHjdauTx8gunMh53WxU9FJ6GBCmkqjCGVWdi6WiUzy8AP0yVM8hLDN/EeCVZS6MT4FzWaBLt+/hqW0UOExp+Rcdm0ndUInSBX3hflG9WSN9UuOvmynMIvlDtjdkvdKqS3fp1+zGFXSYOQP/sTZBZ1Fv9BPLrikcUKrLUsSxcpc79k7aMPeLxMC55eh08ApWRXNty+NjHn1N99PnOeCXEsaUfFDoXwbWtK6uUzRY8toQtuS6dygBdah5qLr8p88cxF80/1emI=
  - secure: s7rilPFXiyTeKncOiPNdFvCqDB6I3fCLMfImqquyOs4sFyScFRShSGyp3OtOHSjlk2f6AVsONIhFpvw3TPdP/i8R1XtFQQ9/Dw1JX08AZB+nyza9TnuMIZK/khReBGJi7lO6508f/z1P6J5eF5CB0tbLNObbbdCBL4rY177/OSUkFyOB1wNVQPPDHgt7gkIC6bP8smc/ew5OBDUwT9ECwr9s1oRn4QEYrfhE4ToVwjQsX/SW4PQJehvFekYZ42JdektgoINnqnKbrBLEvoW6vW1x6x82GwvTxCkOlh3g4ygTJpBoVMS3I1dqkR9fv098xN6NJwv/2bygaMyNyCtJFnu+dcstRexz3OteJPrA8z4s/V+beMVp67FMw4tQpwpUmQvWXIi7oEsa2bgzf/tbCdntuApcxVrK1GbycZ9LHJrfWcqz41lTz1l+jmXh4E+wgP6Z6KVemLJ1/cdYc/4oTWzChAZxrj2XdAsUlXtq9aV9srqp+wfhjRUIwDByoZEqzMm1gYWvGlz6Zb6f3aQnuCoqNfv6WpijdemcIqUq9mq83yuu6Djfwcxdbfy/7l3RZKi9iXQ4UCJuKbjPaB4WrX8vHWUL7ecNA755gToXDFsrDZwhK6FsoBPYTKQwKxrlqwn5pgGb10yaMr/p7lz/a+F7v1JBHl5A9ubixFsnV5s=
